[package]
name = "zettel-web"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = "0.14.26"
pulldown-cmark = { version = "0.9.2", default-features = false }
threadpool = "1.8.1"
